name: "\U0001F41E Bug report"
description: "File a bug report"
title: '🐞Bug'
labels: [Bug,Needs,Triage]

body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exist for the bug you encounter.
    options:
    - label: check
      required: true
- type: textarea
  attributes:
    label:  Current Behavious
    description: A concise description of what you are experiencing.
  validations:
    required: false